name: Java CI in New Repo

on:
  push:
    branches: [ main ]

jobs:
  call-remote-spring-build:
    # Restricts execution so it only runs when commit message contains 'generate build'
    if: contains(github.event.head_commit.message, 'generate build')
    
    # Points to your newly optimized single-job reusable workflow
    uses: manivannancsmca/spring-docker-reusable-workflow/.github/workflows/reusable-spring-boot.yml@main
    with:
      docker-image-name: 'spring-boot-api' # Replace with your preferred Docker Hub repo name
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}